version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: book_management_frontend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://api.paodev.xyz
      - NEXT_PUBLIC_APP_URL=https://book.paodev.xyz
      - NEXT_TELEMETRY_DISABLED=1
    ports:
      - '3000:3000'
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend.rule=Host(`book.paodev.xyz`)
      - traefik.http.routers.frontend.entrypoints=http,https
      - traefik.http.services.frontend.loadbalancer.server.port=3000
      - traefik.http.routers.frontend.tls.certresolver=letsencrypt
    networks:
      - book_management_network
      - coolify

networks:
  book_management_network:
    driver: bridge
  coolify:
    external: true
